# Configuration for Rasa NLU.
language: en  # Default language (can be changed dynamically in the bot)
pipeline:
- name: actions.custom_components.TamilSpokenToWrittenComponent  # Add the custom component
  csv_file_path: "E:/VoiceBot_En_Ta_2.0/actions/informal_queries.csv"  # Add path to CSV file here
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3

# Configuration for Rasa Core.
policies:
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
assistant_id: 20240916-150239-asymptotic-alloy
